src/DARE-FrontEnd/Controllers/ProjectController.cs
using System.Diagnostics;
using BL.Models;
using BL.Models.Settings;
using BL.Models.ViewModels;
using BL.Services;
using DARE_FrontEnd.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DARE_FrontEnd.Controllers
{
    [Authorize]
    public class ProjectController : Controller
    {
        private readonly IDareClientHelper _clientHelper;

        private readonly FormIOSettings _formIOSettings;


        private readonly URLSettingsFrontEnd _URLSettingsFrontEnd;

        public ProjectController(IDareClientHelper client, FormIOSettings formIo,
            URLSettingsFrontEnd URLSettingsFrontEnd)
        {
            _clientHelper = client;

            _formIOSettings = formIo;

            _URLSettingsFrontEnd = URLSettingsFrontEnd;
        }

        private bool IsUserOnProject(SubmissionGetProjectModel proj)
        {
            if (User.IsInRole("dare-control-admin"))
            {
                return true;
            }

            var usersName = "";
            usersName = (from x in User.Claims where x.Type == "preferred_username" select x.Value).FirstOrDefault();
            if (!string.IsNullOrWhiteSpace(usersName) &&
                (from x in proj.Users where x.Name.ToLower().Trim() == usersName.ToLower().Trim() select x).Any())
            {
                return true;
            }

            return false;
        }

        [HttpGet]
        public async Task<IActionResult> GetProject(int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var minioEndpoint = _clientHelper.CallAPIWithoutModel<MinioEndpoint>("/api/Project/GetMinioEndPoint");
            var paramlist = new Dictionary<string, string>();
            paramlist.Add("projectId", id.ToString());
            var projectawait = _clientHelper.CallAPIWithoutModel<SubmissionGetProjectModel>(
                "/api/Project/GetProjectUI/", paramlist);

            Stopwatch stopwatch = new Stopwatch();
            stopwatch.Start();
            await projectawait;
            //Log.Error("projectawait took ElapsedMilliseconds" + stopwatch.ElapsedMilliseconds);
            await minioEndpoint;
            //Log.Error("minioEndpoint took ElapsedMilliseconds" + stopwatch.ElapsedMilliseconds);
            stopwatch.Stop();
            var project = projectawait.Result;

            var userItems2 = project.UsersNotInProject;
            var treItems2 = project.TresNotInProject;

            var userItems = userItems2
                .Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = !string.IsNullOrWhiteSpace(p.FullName)
                        ? p.FullName
                        : (!string.IsNullOrWhiteSpace(p.Name) ? p.Name : $"[id:{p.Id}]")
                })
                .ToList();

            var tres = _clientHelper.CallAPIWithoutModel<List<Tre>>("/api/Tre/GetAllTres/").Result;

            // Process TRE names for display
            var treItems = treItems2
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();


            ViewBag.UserCanDoSubmissions = IsUserOnProject(project);

            ViewBag.minioendpoint = minioEndpoint.Result.Url;
            ViewBag.URLBucket = _URLSettingsFrontEnd.MinioUrl;

            var projectView = new ProjectUserTre()
            {
                Id = project.Id,
                FormData = project.FormData,
                Name = project.Name,
                Users = project.Users,
                StartDate = project.StartDate,
                EndDate = project.EndDate,
                ProjectDescription = project.ProjectDescription,
                ProjectContact = project.ProjectContact,
                ProjectOwner = project.ProjectOwner,
                Tres = project.Tres,
                SubmissionBucket = project.SubmissionBucket,
                OutputBucket = project.OutputBucket,
                MinioEndpoint = minioEndpoint.Result.Url,
                Submissions = project.Submissions.Where(x => x.HasParent == false).ToList(),
                UserItemList = userItems,
                TreItemList = treItems
            };

            //Log.Error("View(projectView) took ElapsedMilliseconds" + stopwatch.ElapsedMilliseconds);
            return View(projectView);
        }


        public IActionResult SubmissionProjectSQL(int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var paramlist = new Dictionary<string, string>();
            paramlist.Add("projectId", id.ToString());
            var project = _clientHelper.CallAPIWithoutModel<SubmissionGetProjectModel>(
                "/api/Project/GetProjectUI/", paramlist).Result;


            ViewBag.UserCanDoSubmissions = IsUserOnProject(project);

            var projectView = new ProjectUserTre()
            {
                Id = project.Id,
                Name = project.Name,
                Submissions = project.Submissions.Where(x => x.HasParent == false).ToList(),
            };

            return View(projectView);
        }


        public IActionResult SubmissionProjectGraphQL(int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var paramlist = new Dictionary<string, string>();
            paramlist.Add("projectId", id.ToString());
            var project = _clientHelper.CallAPIWithoutModel<SubmissionGetProjectModel>(
                "/api/Project/GetProjectUI/", paramlist).Result;

            ViewBag.UserCanDoSubmissions = IsUserOnProject(project);

            var projectView = new ProjectUserTre()
            {
                Id = project.Id,
                Name = project.Name,
                Submissions = project.Submissions.Where(x => x.HasParent == false).ToList()
            };

            return View(projectView);
        }

        public IActionResult SubmissionProjectDemo(int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var paramlist = new Dictionary<string, string>();
            paramlist.Add("projectId", id.ToString());
            var project = _clientHelper.CallAPIWithoutModel<SubmissionGetProjectModel>(
                "/api/Project/GetProjectUI/", paramlist).Result;

            ViewBag.UserCanDoSubmissions = IsUserOnProject(project);

            var projectView = new ProjectUserTre()
            {
                Id = project.Id,
                Name = project.Name,
                Submissions = project.Submissions.Where(x => x.HasParent == false).ToList()
            };

            return View(projectView);
        }

        [HttpGet]
        public IActionResult GetAllProjects()
        {
            var projects = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects/").Result;
            return View(projects);
        }

        [HttpGet]
        [Authorize(Roles = "dare-control-admin")]
        public IActionResult AddUserMembership()
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var projmem = GetProjectUserModel();
            return View(projmem);
        }


        private ProjectUser GetProjectUserModel()
        {
            var projs = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects/").Result;
            var users = _clientHelper.CallAPIWithoutModel<List<BL.Models.User>>("/api/User/GetAllUsers/").Result;

            var projectItems = projs
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();

            var userItems = users
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();

            var projmem = new ProjectUser()
            {
                ProjectItemList = projectItems,
                UserItemList = userItems
            };
            return projmem;
        }

        [HttpGet]
        [Authorize(Roles = "dare-control-admin")]
        public IActionResult AddTreMembership()
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var projmem = GetProjectTreModel();
            return View(projmem);
        }


        private ProjectTre GetProjectTreModel()
        {
            var projs = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects/").Result;
            var users = _clientHelper.CallAPIWithoutModel<List<Tre>>("/api/Tre/GetAllTres/").Result;

            var projectItems = projs
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();

            var treItems = users
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();

            var projmem = new ProjectTre()
            {
                ProjectItemList = projectItems,
                TreItemList = treItems
            };
            return projmem;
        }

        [HttpPost]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> AddUserMembership(ProjectUser model)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var result =
                await _clientHelper.CallAPI<ProjectUser, ProjectUser?>("/api/Project/AddUserMembership", model);
            result = GetProjectUserModel();
            return View(result);
        }

src/DARE-FrontEnd/Controllers/UserController.cs
using BL.Models;
using Users = BL.Models.User;
using BL.Models.Settings;
using BL.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BL.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace DARE_FrontEnd.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IDareClientHelper _clientHelper;
        
        private readonly FormIOSettings _formIOSettings;

        public UserController(IDareClientHelper client, FormIOSettings formIo)
        {
            _clientHelper = client;
            
            _formIOSettings = formIo;
         
        }

        [HttpGet]
        [Authorize(Roles = "dare-control-admin")]
        public IActionResult SaveUserForm(int userId)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var formData = new FormData()
            {
                FormIoUrl = _formIOSettings.UserForm,
                FormIoString = @"{""id"":0}",
                Id = userId
            };
            
            if (userId > 0)
            {
                var paramList = new Dictionary<string, string>();
                paramList.Add("userId", userId.ToString());
                var user = _clientHelper.CallAPIWithoutModel<BL.Models.User?>("/api/User/GetUser/", paramList).Result;
                formData.FormIoString = user?.FormData;
                formData.FormIoString = formData.FormIoString?.Replace(@"""id"":0", @"""Id"":"+userId.ToString(), StringComparison.CurrentCultureIgnoreCase);
            }

            return View(formData);
        }

        [HttpGet]
        public IActionResult GetAllUsers()
        {

            var result = _clientHelper.CallAPIWithoutModel<List<BL.Models.User>>("/api/User/GetAllUsers/").Result;

            return View(result);
        }
        
        
        [HttpGet]
        public IActionResult GetUser(int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var projects = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects/").Result;            
            var paramlist = new Dictionary<string, string>();
            paramlist.Add("userId", id.ToString());
            var result = _clientHelper.CallAPIWithoutModel<BL.Models.User?>(
                "/api/User/GetUser/", paramlist).Result;

            var projectItems2 = projects.Where(p => !result.Projects.Select(x => x.Id).Contains(p.Id)).ToList();          

            var projectItems = projectItems2
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();
           

            ViewBag.ProjectItems = projectItems;

            return View(result);
        }

        [HttpPost]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> UserEditFormSubmission([FromBody] object arg, int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var str = arg?.ToString();

            if (!string.IsNullOrEmpty(str))
            {
                var data = System.Text.Json.JsonSerializer.Deserialize<FormData>(str);
                data.FormIoString = str;

                var result = await _clientHelper.CallAPI<FormData, BL.Models.User>("/api/User/SaveUser", data);

                if (result.Id == 0)
                {
                    TempData["error"] = "";
                    return BadRequest();
                }
                TempData["success"] = "User Save Successfully";
                return Ok(result);
            }
            return BadRequest();
        }

        [HttpGet]
        [Authorize(Roles = "dare-control-admin")]
        public IActionResult AddProjectMembership()
        {

            var projmem = GetProjectUserModel();
            return View(projmem);
        }
     
        [HttpPost]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> AddProjectMembership(ProjectUser model)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var result =
                await _clientHelper.CallAPI<ProjectUser, ProjectUser?>("/api/User/AddProjectMembership", model);
            result = GetProjectUserModel();


            return View(result);
        }

        [HttpGet]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> RemoveProjectFromUser(int userId, int projectId)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var model = new ProjectUser()
            {
                UserId = userId,
                ProjectId = projectId               
            };

            var result = await _clientHelper.CallAPI<ProjectUser, ProjectUser?>("/api/User/RemoveProjectMembership", model);
            TempData["success"] = "Project Remove Successfully";
            return RedirectToAction("GetUser", new { id = userId });
        }

        private ProjectUser GetProjectUserModel()
        {
            var projs = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects/").Result;
            var users = _clientHelper.CallAPIWithoutModel<List<Users>>("/api/User/GetAllUsers/").Result;

            var projectItems = projs
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();

            var userItems = users
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();

            var projmem = new ProjectUser()
            {
                ProjectItemList = projectItems,
                UserItemList = userItems
            };
            return projmem;
        }

        [HttpPost]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> AddProjectList(string Id, string ItemList)
        {
            string[] arr = ItemList.Split(',');
            foreach (string s in arr)
            {
                var model = new ProjectUser()
                {
                    UserId = Int32.Parse(Id),
                    ProjectId = Int32.Parse(s)
                };
                var user =
                await _clientHelper.CallAPI<ProjectUser, ProjectUser?>("/api/Project/CheckUserExists", model);
                if (user.UserId == 0)
                {
                    TempData["error"] = "User not found. Need to Register";
                    return Ok();
                }
                var result =
                await _clientHelper.CallAPI<ProjectUser, ProjectUser?>("/api/User/AddProjectMembership", model);
            }
            TempData["success"] = "Project Added Successfully";
            //return RedirectToAction("GetUser", new { id = Id });
            return Ok();
        }

    }
}

src/DARE-FrontEnd/Views/Project/AddEndpointMembership.cshtml
@model BL.Models.ViewModels.ProjectEndpoint
<div class="row">
    <div class="col-sm-12">
        <h1>Add User to Project</h1>

        

        

        @using (Html.BeginForm("AddEndpointMembership", "Project", FormMethod.Post, new { id = "frmMain" }))
        {
            @Html.AntiForgeryToken()


            <div class="form-group">
                @{
                    @Html.LabelFor(m => m.EndpointId, "Select the TRE")
                    @Html.DropDownListFor(m => m.EndpointId, Model.EndpointItemList, new {@class = "form-control show-tick noBottomMargin"})

                }

                @Html.ValidationMessageFor(m => m.ProjectId, "Select TRE")

            </div>
            <div class="form-group">
                @{
                    @Html.LabelFor(m => m.ProjectId, "Select the project name")
                    @Html.DropDownListFor(m => m.ProjectId, Model.ProjectItemList, new {@class = "form-control show-tick noBottomMargin"})
                    
                }

                @Html.ValidationMessageFor(m => m.ProjectId, "Select Project")

            </div>

            



            <div class="hero-block-1">
                <button  type="submit" class="btn btn-primary"><i class="fas fa-paper-plane"></i>Add TRE Membership</button>
            </div>
        }

    </div>
</div>

src/DARE-FrontEnd/Views/Project/AddTreMembership.cshtml
@model BL.Models.ViewModels.ProjectTre
<div class="row">
    <div class="col-sm-12">
        <h1>Add User to Project</h1>

        

        

        @using (Html.BeginForm("AddTreMembership", "Project", FormMethod.Post, new { id = "frmMain" }))
        {
            @Html.AntiForgeryToken()


            <div class="form-group">
                @{
                    @Html.LabelFor(m => m.TreId, "Select the TRE")
                    @Html.DropDownListFor(m => m.TreId, Model.TreItemList, new {@class = "form-control show-tick noBottomMargin"})

                }

                @Html.ValidationMessageFor(m => m.ProjectId, "Select TRE")

            </div>
            <div class="form-group">
                @{
                    @Html.LabelFor(m => m.ProjectId, "Select the project name")
                    @Html.DropDownListFor(m => m.ProjectId, Model.ProjectItemList, new {@class = "form-control show-tick noBottomMargin"})
                    
                }

                @Html.ValidationMessageFor(m => m.ProjectId, "Select Project")

            </div>

            



            <div class="hero-block-1">
                <button  type="submit" class="btn btn-primary"><i class="fas fa-paper-plane"></i>Add TRE Membership</button>
            </div>
        }

    </div>
</div>

src/DARE-FrontEnd/Views/Project/EditProject.cshtml
@using BL.Models.ViewModels
@model ProjectUserTre
@{
    ViewData["Title"] = "Edit @Model.Name";

    if (Model != null && Model.FormIoUrl.StartsWith('/'))
    {
        Model.FormIoUrl = $"{Context.Request.Scheme}://{Context.Request.Host.Value}" + Model.FormIoUrl;
    }
}

<div class="container-lg mt-4 p-4 bg-white border-1 shadow-sm">

    <div class="d-flex align-items-center justify-content-between">
        <div>
            <h1 class="fs-3 mb-0">@Model.Name</h1>
            <p class="text-muted small mb-0">#@Model.Id</p>
        </div>
        <a href="@Url.Action("GetProject", "Project", new { id = Model.Id })" class="btn btn-sm btn-outline-primary">
            <span>Exit Edit</span>
        </a>
    </div>
    <div class="mt-4">
        <ul class="nav nav-underline border-bottom" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
                <a href="#home-tab" class="nav-link text-dark active" id="home-tab" data-bs-toggle="tab" data-bs-target="#project" role="tab" aria-controls="Project" aria-selected="true">About</a>
            </li>
            <li class="nav-item" role="presentation">
                <a href="#submissions-tab" class="nav-link text-dark" id="submissions-tab" data-bs-toggle="tab" data-bs-target="#submissions" role="tab" aria-controls="submissions" aria-selected="false">
                    <div class="d-flex justify-content-between align-items-center">
                        <span>Submissions</span>
                        <span class="badge bg-dark-blue rounded-pill ms-2">x</span>
                    </div>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a href="#profile-tab" class="nav-link text-dark" id="profile-tab" data-bs-toggle="tab" data-bs-target="#userMembership" role="tab" aria-controls="User Membership" aria-selected="false">
                    <div class="d-flex justify-content-between align-items-center">
                        <span>People</span>
                        <span class="badge bg-dark-blue rounded-pill ms-2">@Model.Users.Count</span>
                    </div>
                </a>
            </li>
            <li class="nav-item" role="presentation">
                <a href="#contact-tab" class="nav-link text-dark" id="contact-tab" data-bs-toggle="tab" data-bs-target="#tre" role="tab" aria-controls="Tre" aria-selected="false">
                    <div class="d-flex justify-content-between align-items-center">
                        <span>TREs</span>
                        <span class="badge bg-dark-blue rounded-pill ms-2">@Model.Tres.Count</span>
                    </div>
                </a>
            </li>
        </ul>


        <div class="tab-content py-5" id="myTabContent">
            <div class="tab-pane fade show active" id="project" role="tabpanel" aria-labelledby="home-tab">
                <div class="row">
                    <div class="col-md-6">
                        
                        <div id="errorMsg" style="color: #D63301; background-color: #FFCCBA; background-image: url('https://i.imgur.com/GnyDvKN.png'); border: 1px solid;margin: 10px 0px;padding: 15px 10px 15px 50px;background-repeat: no-repeat;background-position: 10px center;display: none;"></div>

                        <div id="formio"> <img src="~/img/loader.gif" width="30" height="30" alt="Loading..." /> </div>
                        <button id="ExternalSubmit" type="submit" class="btn btn-md btn-primary mr-2">Submit</button>

                        <div id="SubmitForReview" class="text-left g-width-400 g-bg-white g-overflow-y-auto g-pa-20 g-overflow-y-auto" style="display: none;">
                            <div class="text-right">
                                <button type="button" class="btn btn-link mr-2 text-decoration-none" onclick="Custombox.modal.close();">
                                    <em class="hs-admin-close g-font-size-22"></em>
                                </button>
                            </div>
                        </div>
                        <script>
                            window.onload = function () {
                                renderForm("@Model.FormIoUrl", @Html.Raw(Model.FormData), '/Project/ProjectFormSubmission/@Url.ActionContext.RouteData.Values["id"]', false, 'formio', "/Project/GetAllProjects");
                            }
                        </script>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="submissions" role="tabpanel" aria-labelledby="submissions-tab">
                <div class="mt-2 mb-2">
                    <button type="button" class="btn btn-sm btn-primary mb-3" id="addSubmission">Add Submission</button>
                </div>
                <p>
                    Minio URL: <a href="#">http://Html.Raw(Model.MinioEndpoint)</a><br />
                    Submission Bucket: @Html.Raw(Model.SubmissionBucket)<br />
                    Output Bucket: @Html.Raw(Model.OutputBucket)
                </p>
                
            </div>
            <div class="tab-pane fade" id="userMembership" role="tabpanel" aria-labelledby="profile-tab">
                <div class="mt-2 mb-2">
                    <button type="button" class="btn btn-sm btn-primary mb-3" id="addUser">Add User</button>
                </div>
                <div class="row">
                    <div class="col-12">
                        <ul class="list-group">
                            @foreach (var user in Model.Users)
                            {
                                <li class="list-group-item">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <a href="@Url.Action("GetUser", "User", new { id = user.Id })" class="fs-6 fw-bold">@user.Name</a>
                                        <a href="@Url.Action("RemoveUserFromProject", "Project",new{ProjectId=Model.Id,UserId=@user.Id})">
                                            <span class="fa fa-trash" data-bs-toggle="tooltip" data-bs-title="Remove user from project"></span>
                                        </a>
                                    </div>

                                </li>
                            }
                        </ul>
                    </div>
                </div>

            </div>
            <div class="tab-pane fade" id="tre" role="tabpanel" aria-labelledby="contact-tab">
                <div class="mt-2 mb-2">
                    <button type="button" class="btn btn-sm btn-primary mb-3" id="addTre">Add TRE</button>
                </div>
                <div class="row">
                    <div class="col-12">
                        <ul class="list-group">
                            @foreach (var tre in Model.Tres)
                            {
                                <li class="list-group-item">
                                    <div class="d-flex align-items-center justify-content-between">
                                        <a href="@Url.Action("GetATre", "Tre", new { id = tre.Id })" class="fs-6 fw-bold">@tre.Name</a>
                                        <a href="@Url.Action("RemoveTreFromProject", "Project",new{ProjectId=Model.Id,TreId=tre.Id})">
                                            <span class="fa fa-trash" data-bs-toggle="tooltip" data-bs-title="Remove TRE from project"></span>
                                        </a>
                                    </div>

                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade bd-user-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="userModal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add User</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="UserList">
                                    <caption>Users on project</caption>
                                    @foreach (var user in Model.UserItemList)
                                    {
                                        <tr>
                                            <td><input type="checkbox" value="@user.Value" id="@user.Value" name="selectedUser"/></td>
                                            <td>@user.Text</td>
                                        </tr>
                                    }
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="SaveUserList(@Model.Id)">Add</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade bd-tre-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="treModal">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add TRE</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-12">
                            <div class="table-responsive">
                                <table class="table table-bordered" id="TreList">
                                    <caption>List of tres on project</caption>
                                    @foreach (var tre in Model.TreItemList)
                                    {
                                        <tr>
                                            <td><input type="checkbox" value="@tre.Value" id="Tre_@tre.Value" name="selectedTre"/></td>
                                            <td>@tre.Text</td>
                                        </tr>
                                    }
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="SaveTreList(@Model.Id)">Add</button>
                </div>
            </div>
        </div>
    </div>
</div>

src/DARE-FrontEnd/Views/Project/GetProjectBuckets.cshtml
@using BL.Models.ViewModels
@model ProjectUserTre
@{
    ViewData["Title"] = "Edit @Model.Name";
}

Minio URL: http://@Html.Raw(Model.MinioEndpoint) 

Submission Bucket: @Html.Raw(Model.SubmissionBucket) 
Output Bucket: @Html.Raw(Model.OutputBucket)