src/Data-Egress-UI/Controllers/DataEgressCredentialsController.cs
using BL.Models;
using BL.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BL.Models.APISimpleTypeReturns;

namespace Data_Egress_UI.Controllers
{
    [Authorize(Roles = "data-egress-admin")]
    public class DataEgressCredentialsController : Controller
    {
        private readonly IDataEgressClientHelper _clientHelper;
        public DataEgressCredentialsController(IDataEgressClientHelper client)
        {
            _clientHelper = client;
        }
        [HttpGet]
        public async Task<IActionResult> UpdateCredentialsAsync()
        {
            var valid = await _clientHelper.CallAPIWithoutModel<BoolReturn>("/api/TreCredentials/EgressCheckCredentialsAreValid");
            return View(new KeycloakCredentials()
                { Valid = valid.Result });
        }
        [HttpPost]
        public async Task<IActionResult> UpdateCredentials(KeycloakCredentials credentials)
        {
            if (ModelState.IsValid)
            {
                credentials =
                    await _clientHelper.CallAPI<KeycloakCredentials, KeycloakCredentials>(
                        "/api/TreCredentials/EgressUpdateCredentials", credentials);
                if (credentials.Valid)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View(credentials);
                }
            }
            else
            {
                return View(credentials);
            }
        }
    }
}

src/Data-Egress-UI/Controllers/TreCredentialsController.cs
using BL.Models;
using BL.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BL.Models.APISimpleTypeReturns;

namespace Data_Egress_UI.Controllers
{
    [Authorize(Roles = "data-egress-admin")]
    public class TreCredentialsController : Controller
    {
        private readonly IDataEgressClientHelper _clientHelper;
        public TreCredentialsController(IDataEgressClientHelper client)
        {
            _clientHelper = client;
        }


        [HttpGet]
        public async Task<IActionResult> UpdateCredentialsAsync()
        {
            var valid = await _clientHelper.CallAPIWithoutModel<BoolReturn>("/api/TreCredentials/CheckCredentialsAreValid");


            return View(new KeycloakCredentials()
            { Valid = valid.Result })
                ;
        }

        [HttpPost]

        public async Task<IActionResult> UpdateCredentials(KeycloakCredentials credentials)
        {

            if (ModelState.IsValid)
            {


                credentials =await _clientHelper.CallAPI<KeycloakCredentials, KeycloakCredentials>(
                        "/api/TreCredentials/UpdateCredentials", credentials);
                if (credentials.Valid)
                {
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    return View(credentials);
                }
            }
            else
            {
                return View(credentials);
            }

        }

    }
}

src/Data-Egress-UI/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration;
@inject IConfiguration Configuration
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" shrink-to-fit="no" />
	<title>@ViewData["Title"] - Data Egress</title>
	<link rel="stylesheet" href="~/css/fontawesome.css" />
	<link rel="stylesheet" href="~/css/brands.css" />
	<link rel="stylesheet" href="~/css/solid.css" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/datatables.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<script src="~/js/clipboard.min.js"></script>
	<link rel="stylesheet" href="https://use.typekit.net/tyz0nfb.css">
</head>
<body class="d-flex flex-column h-100">
	<header>
		<nav class="autohide navbar navbar-expand-md navbar-toggleable-md navbar-light bg-white box-shadow mb-3">
			<div class="container-fluid">
				<a class="navbar-brand me-5 fw-bold" asp-area="" asp-controller="Home" asp-action="Index">Data Egress</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span id="nav-icon3" class="navbar-toggler-icon">
						<span></span>
						<span></span>
						<span></span>
						<span></span>
					</span>
				</button>
				<div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
					<ul class="navbar-nav flex-grow-1">
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Data" asp-action="GetAllEgressesuUnprocessed">Requests</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="TreCredentials" asp-action="UpdateCredentials">Update Tre Credentials</a>
						</li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="DataEgressCredentials" asp-action="UpdateCredentials">Update Egress Credentials</a>
						</li>
						<li class="mobile-account-nav">
							<hr class="mobile-account-nav dropdown-divider" />
						</li>
						<li class="mobile-account-nav nav-item"><a class="nav-link text-dark" href="#">Account</a></li>
						<li class="mobile-account-nav nav-item"><a class="nav-link text-dark" href="@Configuration.GetSection("Helpdesk")["URL"]">Helpdesk</a></li>
						<li class="mobile-account-nav nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
						</li>
					</ul>
				</div>
				<div class="account-nav align-items-center">
					<div class="nav-item dropdown">
						<a class="nav-link text-dark dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
							@User?.FindFirst("name")?.Value
						</a>
						<ul class="dropdown-menu dropdown-right" aria-labelledby="navbarDropdown">
							<li><a class="dropdown-item" href="@Configuration.GetSection("DataEgressKeyCloakSettings")["AccountManagementURL"]">Account</a></li>
							<li><a class="dropdown-item" href="@Configuration.GetSection("Helpdesk")["URL"]">Helpdesk</a></li>
							<li><hr class="dropdown-divider"></li>
							@if (@User?.FindFirst("name")?.Value == null)
							{
								<li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Logout">Login</a></li>
							}
							else
							{
								<li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a></li>
							}

						</ul>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<main role="main" class="pb-3">
		@RenderBody()
	</main>

	<footer class="mt-auto footer text-muted">
		<div class="footer-top py-lg-4 py-5">
			<div class="container">
				<div class="row align-items-center gy-5 gx-sm-5 text-center">
					<div class="col-lg-4 col-md-12 text-end-md">
						<a href="https://dareuk.org.uk/" target="_blank" class="dare-logo pe-lg-5 pe-0" rel="noopener">DARE UK</a>
					</div>
					<div class="col-lg-2 col-sm-4">
						<a href="https://www.ukri.org/" target="_blank" rel="noopener"><img src="/img/ukri-logo.png.webp" class="img-fluid" alt="UKRI logo" /></a>
					</div>
					<div class="col-lg-2 col-sm-4">
						<a href="https://www.hdruk.ac.uk/" target="_blank" rel="noopener"><img src="/img/hdruk-logo.png.webp" class="img-fluid" alt="HDRUK logo" style="max-height:55px;" /></a>
					</div>
					<div class="col-lg-2 col-sm-4">
						<a href="https://www.adruk.org/" target="_blank" rel="noopener"><img src="/img/adruk-logo.png.webp" class="img-fluid" alt="ADRUK logo" /></a>
					</div>
				</div>


			</div>
		</div>
		<div class="footer-bottom">
			<div class="container text-md-start text-center">
				<ul class="nav mb-2 flex-md-row flex-column">
					<li class="nav-item">
						<a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="TermsAndConditions">Terms and Conditions</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="PrivacyPolicy">Privacy Policy</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-light" href="https://dareuk.org.uk/about/" target="_blank" rel="noopener">About DARE UK</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-light" href="https://dareuk.org.uk/contact/" target="_blank" rel="noopener">Contact Us</a>
					</li>
				</ul>
				<p class="text-light mt-md-0 mt-5 mb-0">&copy;DARE UK - DATA Egress @DateTime.Now.Year. All rights reserved.</p>
			</div>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/bootstrap-history-tabs.js"></script>
	<script src="~/js/datatables.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
	<script>
		$('#fileList').DataTable({
			columns: [
				null,
				null,
				null,
				null,
				null,
				{ orderable: false }
			],
			order: [[0, 'desc']]
		});

		$(document).ready(function () {
			if (window.location.href.indexOf("GetAllEgresses") > -1) {
				$('.egress-menu li:first-child .nav-link').addClass('active');
			}
			if (window.location.href.indexOf("GetAllUnprocessedEgresses") > -1) {
				$('.egress-menu li:last-child .nav-link').addClass('active');
			}
		});
	</script>
</body>
</html>