src/DARE-FrontEnd/Controllers/HomeController.cs
using BL.Models.APISimpleTypeReturns;
using BL.Models;
using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Mvc;
using BL.Services;
using BL.Models.ViewModels;
using NuGet.Protocol;
using System.Linq;
using Serilog;
using Microsoft.CodeAnalysis.Elfie.Diagnostics;
using DARE_FrontEnd.Models;

namespace DARE_FrontEnd.Controllers
{

    [AllowAnonymous]
    public class HomeController : Controller
    {

        private readonly IDareClientHelper _clientHelper;
        private readonly IConfiguration _configuration;
        private readonly UIName _UIName;


        public HomeController(IDareClientHelper client, IConfiguration configuration, UIName uIName)
        {
            _clientHelper = client;
            _configuration = configuration;
            _UIName = uIName;
        }

        public IActionResult Index()
        {
            ViewBag.getAllProj = 0;
            ViewBag.getAllSubs = 0;
            ViewBag.getAllUsers = 0;
            ViewBag.getAllTres = 0;
            ViewBag.UIName = _UIName.Name;


            try
            {
                var getAllProj = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects").Result;
                ViewBag.getAllProj = getAllProj.Count;


                var getAllSubs = _clientHelper
                    .CallAPIWithoutModel<List<Submission>>("/api/Submission/GetAllSubmissions").Result
                    .Where(x => x.Parent == null).ToList();
                ViewBag.getAllSubs = getAllSubs.Count;

                var getAllUsers = _clientHelper.CallAPIWithoutModel<List<User>>("/api/User/GetAllUsers").Result;
                ViewBag.getAllUsers = getAllUsers.Count;

                var getAllTres = _clientHelper.CallAPIWithoutModel<List<Tre>>("/api/Tre/GetAllTres").Result;
                ViewBag.getAllTres = getAllTres.Count;
            }
            catch (Exception e)
            {
                Log.Warning(e, "{Function} Unable to call api. Might just be initialisation issue");

            }


            foreach (var Claim in User.Claims)
            {
                Log.Debug($"User has Claim {Claim.ToString()}");
            }


            return View();
        }

        [HttpPost]
        public IActionResult SearchView(string searchString)
        {
            List<Project> results = SearchData(searchString);

            {
                if (results != null)
                {
                    ViewBag.SearchResults = results;
                    ViewBag.SearchString = searchString;
                }
                else
                {
                    //results = new List<Project>();
                    ViewBag.SearchResults = "No search results found.";
                    //ViewBag.SearchString = "No Results found";
                }
                return View();
            }
        }

        //private helpers
        private List<Project> SearchData(string searchString)
        {
            try
            {
                var paramlist = new Dictionary<string, string>();
                paramlist.Add("searchString", searchString);
                var results = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetSearchData/", paramlist).Result.ToList();
                return results;
            }
            catch (Exception ex)
            {
                Log.Error(ex.ToString());
                return null;
            }
        }
       

        [Authorize]
        public IActionResult LoggedInUser()
        {
            if(User.Identity.IsAuthenticated == false) {
                return RedirectToAction("Index", "Home");
            }

            // This var is always in lower case/case-insensitive because we are getting it from KeyCloak 
            var preferedUsername = (from x in User.Claims where x.Type == "preferred_username" select x.Value).First();
            
            var getAllProj = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects").Result;
            ViewBag.getAllProj = getAllProj;

            var getAllSubs = _clientHelper.CallAPIWithoutModel<List<Submission>>("/api/Submission/GetAllSubmissions").Result.Where(x => x.Parent == null).ToList();
            ViewBag.getAllSubs = getAllSubs.Count;

            var getAllUsers = _clientHelper.CallAPIWithoutModel<List<User>>("/api/User/GetAllUsers").Result;
            ViewBag.getAllUsers = getAllUsers.Count;

            var getAllTres = _clientHelper.CallAPIWithoutModel<List<Tre>>("/api/Tre/GetAllTres").Result;
            ViewBag.getAllTres = getAllTres.Count;

            var userOnProjList = new List<User>();
            var userOnProjListProj = new List<Project>();
            var projectList = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects").Result.ToList();
            foreach (var proj in projectList)
            {
                foreach (var user in proj.Users)
                {
                    // Making sure that the username getting from the DB is lowered/case-insensitive as well as username from KeyCloak
                    var loweredUserName = user.Name.ToLower();
                    if (loweredUserName == preferedUsername)
                    {
                        userOnProjListProj.Add(proj);

                        userOnProjList.Add(user);
                    }
                }
            }
            var userOnProjectsCount = userOnProjList.ToList().Count;
            ViewBag.userOnProjectCount = userOnProjectsCount;

            var userWroteSubList = new List<User>();
            var userWroteSubListSub = new List<Submission>();
            var subList = getAllSubs;
            foreach (var sub in subList)
            {

                    if (sub.SubmittedBy.Name == preferedUsername)
                {
                    userWroteSubListSub.Add(sub);
                    userWroteSubList.Add(sub.SubmittedBy);
                
                }

            }
            var userWroteSubCount = userWroteSubList.ToList().Count;
            var distintProj = userOnProjListProj.Distinct();
            var distinctSub = userWroteSubListSub.Distinct();
            ViewBag.userWroteSubCount = userWroteSubCount;

            var userModel = new User
            {
                Name = User.Identity.Name,

                Projects = distintProj.ToList(),

                Submissions = distinctSub.ToList(),
        };
            
            return View(userModel);
        }

      


        public IActionResult TermsAndConditions()
        {
            return View();
        }
        public IActionResult PrivacyPolicy()
        {
            return View();
        }
    }

}

src/DARE-FrontEnd/Controllers/TreController.cs
using BL.Models;
using BL.Models.ViewModels;
using BL.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using BL.Models.Settings;
using Newtonsoft.Json;

namespace DARE_FrontEnd.Controllers
{
    [Authorize]
    public class TreController : Controller
    {
        private readonly IDareClientHelper _clientHelper;

        private readonly FormIOSettings _formIOSettings;

        public TreController(IDareClientHelper client, FormIOSettings formIo)
        {
            _clientHelper = client;

            _formIOSettings = formIo;
        }

        [HttpGet]
        [Authorize(Roles = "dare-control-admin")]
        public IActionResult SaveATre(int treId)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var formData = new FormData()
            {
                FormIoUrl = _formIOSettings.TreForm,
                FormIoString = @"{""id"":0}",
                Id = treId
            };

            if (treId > 0)
            {
                var paramList = new Dictionary<string, string>();
                paramList.Add("treId", treId.ToString());
                var tre = _clientHelper.CallAPIWithoutModel<Tre>("/api/Tre/GetATre/", paramList).Result;
                formData.FormIoString = tre?.FormData;
                formData.FormIoString = formData.FormIoString?.Replace(@"""id"":0", @"""Id"":" + treId.ToString(),
                    StringComparison.CurrentCultureIgnoreCase);
            }

            return View(formData);
        }


        [HttpGet]
        public IActionResult GetAllTres()
        {
            var tres = _clientHelper.CallAPIWithoutModel<List<Tre>>("/api/Tre/GetAllTres/").Result;

            return View(tres);
        }

        [HttpGet]
        public IActionResult GetATre(int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var paramlist = new Dictionary<string, string>();
            paramlist.Add("treId", id.ToString());
            var Tre = _clientHelper.CallAPIWithoutModel<Tre?>(
                "/api/Tre/GetATre/", paramlist).Result;

            return View(Tre);
        }


        [HttpPost]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> TreFormSubmission([FromBody] object arg, int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var str = arg?.ToString();

            if (!string.IsNullOrEmpty(str))
            {
                var data = System.Text.Json.JsonSerializer.Deserialize<FormData>(str);
                data.FormIoString = str;


                var json = System.Text.Json.JsonSerializer.Serialize(data);
                var content = new StringContent(json, System.Text.Encoding.UTF8, "application/json");

                var response = await _clientHelper.CallAPI("/api/Tre/SaveTre", content);

                if (response.IsSuccessStatusCode)
                {
                    var result = await response.Content.ReadAsStringAsync();
                    var tre = JsonConvert.DeserializeObject<Tre>(result);
                    TempData["success"] = "Tre saved Successfully";
                    return Ok(tre);
                }
                else
                {
                    var errorMessage = await response.Content.ReadAsStringAsync();
                    return BadRequest(errorMessage);
                }
            }

            return BadRequest("Invalid data");
        }
    }
}

src/DARE-FrontEnd/Controllers/UserController.cs
using BL.Models;
using Users = BL.Models.User;
using BL.Models.Settings;
using BL.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BL.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace DARE_FrontEnd.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IDareClientHelper _clientHelper;
        
        private readonly FormIOSettings _formIOSettings;

        public UserController(IDareClientHelper client, FormIOSettings formIo)
        {
            _clientHelper = client;
            
            _formIOSettings = formIo;
         
        }

        [HttpGet]
        [Authorize(Roles = "dare-control-admin")]
        public IActionResult SaveUserForm(int userId)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var formData = new FormData()
            {
                FormIoUrl = _formIOSettings.UserForm,
                FormIoString = @"{""id"":0}",
                Id = userId
            };
            
            if (userId > 0)
            {
                var paramList = new Dictionary<string, string>();
                paramList.Add("userId", userId.ToString());
                var user = _clientHelper.CallAPIWithoutModel<BL.Models.User?>("/api/User/GetUser/", paramList).Result;
                formData.FormIoString = user?.FormData;
                formData.FormIoString = formData.FormIoString?.Replace(@"""id"":0", @"""Id"":"+userId.ToString(), StringComparison.CurrentCultureIgnoreCase);
            }

            return View(formData);
        }

        [HttpGet]
        public IActionResult GetAllUsers()
        {

            var result = _clientHelper.CallAPIWithoutModel<List<BL.Models.User>>("/api/User/GetAllUsers/").Result;

            return View(result);
        }
        
        
        [HttpGet]
        public IActionResult GetUser(int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var projects = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects/").Result;            
            var paramlist = new Dictionary<string, string>();
            paramlist.Add("userId", id.ToString());
            var result = _clientHelper.CallAPIWithoutModel<BL.Models.User?>(
                "/api/User/GetUser/", paramlist).Result;

            var projectItems2 = projects.Where(p => !result.Projects.Select(x => x.Id).Contains(p.Id)).ToList();          

            var projectItems = projectItems2
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();
           

            ViewBag.ProjectItems = projectItems;

            return View(result);
        }

        [HttpPost]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> UserEditFormSubmission([FromBody] object arg, int id)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var str = arg?.ToString();

            if (!string.IsNullOrEmpty(str))
            {
                var data = System.Text.Json.JsonSerializer.Deserialize<FormData>(str);
                data.FormIoString = str;

                var result = await _clientHelper.CallAPI<FormData, BL.Models.User>("/api/User/SaveUser", data);

                if (result.Id == 0)
                {
                    TempData["error"] = "";
                    return BadRequest();
                }
                TempData["success"] = "User Save Successfully";
                return Ok(result);
            }
            return BadRequest();
        }

        [HttpGet]
        [Authorize(Roles = "dare-control-admin")]
        public IActionResult AddProjectMembership()
        {

            var projmem = GetProjectUserModel();
            return View(projmem);
        }
     
        [HttpPost]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> AddProjectMembership(ProjectUser model)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var result =
                await _clientHelper.CallAPI<ProjectUser, ProjectUser?>("/api/User/AddProjectMembership", model);
            result = GetProjectUserModel();


            return View(result);
        }

        [HttpGet]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> RemoveProjectFromUser(int userId, int projectId)
        {
            if (!ModelState.IsValid) // SonarQube security
            {
                return View("/");
            }

            var model = new ProjectUser()
            {
                UserId = userId,
                ProjectId = projectId               
            };

            var result = await _clientHelper.CallAPI<ProjectUser, ProjectUser?>("/api/User/RemoveProjectMembership", model);
            TempData["success"] = "Project Remove Successfully";
            return RedirectToAction("GetUser", new { id = userId });
        }

        private ProjectUser GetProjectUserModel()
        {
            var projs = _clientHelper.CallAPIWithoutModel<List<Project>>("/api/Project/GetAllProjects/").Result;
            var users = _clientHelper.CallAPIWithoutModel<List<Users>>("/api/User/GetAllUsers/").Result;

            var projectItems = projs
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();

            var userItems = users
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name })
                .ToList();

            var projmem = new ProjectUser()
            {
                ProjectItemList = projectItems,
                UserItemList = userItems
            };
            return projmem;
        }

        [HttpPost]
        [Authorize(Roles = "dare-control-admin")]
        public async Task<IActionResult> AddProjectList(string Id, string ItemList)
        {
            string[] arr = ItemList.Split(',');
            foreach (string s in arr)
            {
                var model = new ProjectUser()
                {
                    UserId = Int32.Parse(Id),
                    ProjectId = Int32.Parse(s)
                };
                var user =
                await _clientHelper.CallAPI<ProjectUser, ProjectUser?>("/api/Project/CheckUserExists", model);
                if (user.UserId == 0)
                {
                    TempData["error"] = "User not found. Need to Register";
                    return Ok();
                }
                var result =
                await _clientHelper.CallAPI<ProjectUser, ProjectUser?>("/api/User/AddProjectMembership", model);
            }
            TempData["success"] = "Project Added Successfully";
            //return RedirectToAction("GetUser", new { id = Id });
            return Ok();
        }

    }
}

src/DARE-FrontEnd/Views/Home/Index.cshtml
@model BL.Models.User

@{
    var getAllProj = @ViewBag.getAllProj;
    var getAllSubs = @ViewBag.getAllSubs;
    var getAllUsers = @ViewBag.getAllUsers;
    var getAllTres = @ViewBag.getAllTres;
    var searchResults = @ViewBag.SearchResults;
    var Name = @ViewBag.UIName;
    ViewData["Title"] = "Home";
}


<div class="home-banner text-center">
    <h1 class="display-5 text-light">Safe &amp; Transparent Research</h1>
    <p class="text-light fs-6 mb-5">Search and discover the types of research this trusted platform is enabling for public good.</p>
    <div class="col-xl-4 col-lg-6 col-md-8 col-sm-10 mx-auto">
        <form class="" asp-controller="Home" asp-action="SearchView">
            <div class="input-group mb-3 px-4">
                <input type="search" name="searchString" value="" placeholder="Search..." class="form-control" aria-label="Search" aria-describedby="button-addon2">
                <button class="btn btn-primary" type="submit" id="button-addon2">Go</button>
            </div>
        </form>
    </div>
</div>
<div class="container mt-5">

    <div class="row row-cols-1 row-cols-sm-2 row-cols-lg-4 g-md-5 g-4">
        <div class="col">
            <a asp-area="" asp-controller="Submission" asp-action="GetAllSubmissions" class="card shadow-sm">
                <img class="card-img-top" src="/img/data-image.jpg" alt="Submissions image" />
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4 class="m-0 text-dark fs-5">Submissions</h4>
                        <span class="badge bg-dark-blue rounded-pill">@getAllSubs</span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col">
            <a asp-area="" asp-controller="Project" asp-action="GetAllProjects" class="card shadow-sm">
                <img class="card-img-top" src="/img/shutterstock_1081970570-Reduced-740x481.jpg" alt="Projects image" />
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4 class="m-0 text-dark fs-5">Projects</h4>
                        <span class="badge bg-dark-blue rounded-pill">@getAllProj</span>
                    </div>
                </div>
            </a>
        </div>
        <div class="col">
            <a asp-area="" asp-controller="User" asp-action="GetAllUsers" class="card shadow-sm">
                <img class="card-img-top" src="/img/shutterstock_376975414-740x481.jpg.webp" alt="People image" />
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4 class="m-0 text-dark fs-5">People</h4>
                        <span class="badge bg-dark-blue rounded-pill">@getAllUsers</span>
                    </div>
                </div>
            </a>
        </div>

        <div class="col">
            <a asp-area="" asp-controller="Tre" asp-action="GetAllTres" class="card shadow-sm">
                <img class="card-img-top" src="/img/about-banner.jpg" alt="TREs image" />
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center">
                        <h4 class="m-0 text-dark fs-5">TREs</h4>
                        <span class="badge bg-dark-blue rounded-pill">@getAllTres</span>
                    </div>
                </div>
            </a>
        </div>

    </div>
</div>
<div class="container my-5">
    <div class="col-lg-8 mx-auto">
        <h3 class="text-center mb-4">About @Name</h3>

        <p>@Name was developed by UKRI's DARE UK to support fast and efficient sharing, linkage, and advanced analysis of sensitive data in an ethical and secure manner.</p>
        <p>@Name allows approved researchers to work with a ‘federated’ network of trusted research environments (TREs) by querying the data held by different TREs from one location - meaning the data doesn't have to be joined or moved from its secure location and the researcher saves time by submitting a query once for multiple TREs.</p>
        <p>The platform adopts a transparent approach and is open for the public to see what research is being conducted across the different TREs and also opens up the possibility of more collaboration in the research community.</p>
    </div>
</div>

src/DARE-FrontEnd/Views/Home/SearchView.cshtml
@{
    var searchResults = @ViewBag.SearchResults;
    var searchString = @ViewBag.SearchString;

    ViewData["Title"] = "Search Results";
}
<div class="container-lg mt-4 p-4 bg-white border-1 shadow-sm">
    @if (searchResults != null && searchString != null)
    {
        <h3 class="mb-3"><span class="text-muted">Search Results for:</span>@searchString.ToString()</h3>
        <form class="d-none d-lg-block" asp-controller="Home" asp-action="SearchView">
            <div class="input-group w-50 mb-5">
                <input type="search" name="searchString" value="" placeholder="@searchString.ToString()" class="form-control form-control-sm" aria-label="Search" aria-describedby="button-addon2">
                <button class="btn btn-sm btn-primary" type="submit" id="button-addon2">Go</button>
            </div>
        </form>
        @*<ul>
    @foreach (var project in searchResults)
    {
    <li><a href="@Url.Action("GetProject", "Project", new { id = project.Id })">@project.Name </a> </li>
    <ul>
    @foreach (var user in project.Users)
    {
    <li><a href="@Url.Action("GetUser", "User", new { id = user.Id })">@user.Name </a></li>
    }
    </ul>
    <ul>
    @foreach (var tre in project.Tres)
    {
    <li><a href="@Url.Action("GetATre", "Tre", new { id = tre.Id })">@tre.Name</a></li>
    }
    </ul>
    }
    </ul>*@
        <ul>
            @foreach (var project in searchResults)

            { 
               
                    <li><a href="@Url.Action("GetProject", "Project", new { id = project.Id })">Project: @project.Name </a> </li>

             
                <ul>
                    @foreach (var user in project.Users) 
                    {
            
                            <li><a href="@Url.Action("GetUser", "User", new { id = user.Id })">User: @user.Name </a></li>
                     
                    }
                </ul>
                <ul>
                    @foreach (var tre in project.Tres)
                    {


                        <li><a href="@Url.Action("GetATre", "Tre", new { id = tre.Id })">Tres: @tre.Name</a></li>
                      
                    }
                </ul>
                <ul>
                    @foreach (var submissions in project.Submissions)
                    {
                        if (submissions.Parent == null )
                        {
                            <li><a href="@Url.Action("GetATre", "Tre", new { id = submissions.Id })">Submissions: @submissions.TesName</a></li>
                        }
                    }
                </ul>
            }
        </ul>
    }
    else


    {
        <h2>Results</h2>

        <h3>No results for this Query</h3>
    }
</div>